title: Project
  
files: true
  sortable: true
  fields:
    author:
      label: Author
      type: text
    copyright:
      label: Copyright
      type: text
    date: true
      label: Date
      type: date
    time: true
      label: Time
      type: time
    caption:
      label: Caption
      type: textarea
    number:
      label: number
      type: text

fields:
  title:
    label: Titel
    type:  text

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4
  
  twitter: 
    label: Twitter
    type: text
    placeholder: @username
    icon: twitter
    width: 2/4

  twitterurl:
    label: Twitter Url
    type: text
    icon: twitter 
    width: 2/4 

  text:
    label: Text
    type:  textarea
