title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4
  
  twitter: 
    label: Twitter
    type: text
    placeholder: @username
    icon: twitter
    width: 2/4

  twitterurl:
    label: Twitter Url
    type: text
    icon: twitter 
    width: 2/4 

  text:
    label: Text
    type:  textarea
